### PR TITLE
CRITICAL: Install important dependency to make this work

### PR DESCRIPTION
**Pull request by miguelgargallo**
This will allow more users to use and enjoy this amazing project!

### CODE REVIEW

**Comment by scosman** [comment]
Auth-ui-shared is already in package-lock via dependency chain. Why add it to the package.json directly?

**Comment by scosman** [comment]
Closing: implicit dependency, will still be installed by "npm install". Let me know if I'm wrong or missed something.

**Comment by wassim-ben-amor** [comment]
Hello @scosman,
When using a different package manager like `pnpm`, it generates a fresh `pnpm-lock.yaml` that doesn't include `@supabase/auth-ui-shared`, even though it's used.

I recommend explicitly adding it to package.json since it's directly imported. This avoids ghost dependencies and aligns with pnpm best practices around strict dependency resolution.

**Comment by scosman** [comment]
@wassim-ben-amor `auth-ui-svelte` which is in the package.lock depends on `auth-ui-shared`, so pnpm should pick it up as a dependency. Is it not?

**Pull request closed without merging**
