### PR TITLE
Svelte 5 Migration

### PR DESCRIPTION
**Pull request by evlim**
Required for Svelte 5 to prevent: https://github.com/sveltejs/svelte/issues/9785

## Summary by CodeRabbit

- **New Features**
	- Enhanced state management across various components for improved reactivity.
	- Introduced new interfaces for props in several components, improving type safety and clarity.
	- Updated rendering logic to support conditional rendering of child components.

- **Bug Fixes**
	- Improved handling of data properties to ensure better binding and reactivity.

- **Documentation**
	- Updated comments and accessibility features in several components.

- **Refactor**
	- Streamlined prop handling by transitioning from direct exports to destructuring from `$props()`.
	- Replaced `<slot />` syntax with `{@render children?.()}` for more explicit rendering control.

### CODE REVIEW

**Comment by scosman** [comment]
Oh cool - does the project otherwise work with svelte 5? I've been meaning to try it.

For this, we should just ignore any validation issues for this file. Email html is.... awful. To work in all email clients you need to work with a random old subset of proper html. This template was from a repo where they tested to make sure it works in all clients (Yahoo mail, etc). Not using tbody was intentional, even if modern linters complain.

We could use inline ignore comments, or file-based ignores. Want to take a stab at that?

**Comment by evlim** [comment]
Somehow the migration works (with some minor adjustments) if we fix the email html.
However, without that the build would fail.

Will check again later

**Comment by evlim** [comment]
`x Build failed in 1.97s
error during build:
[vite-plugin-svelte] [plugin vite-plugin-svelte] src/lib/emails/welcome_email_html.svelte (119:6): src/lib/emails/welcome_email_html.svelte:119:6 `<tr>` is invalid inside `<table>`
file: /home/runner/work/CMSaasStarter/CMSaasStarter/src/lib/emails/welcome_email_html.svelte:119:6

 117 |        bgcolor="#f4f5f6"
 118 |      >
 119 |        <tr>
                  ^
 120 |          <td
 121 |            style="font-family: Helvetica, sans-serif; font-size: 16px; vertical-align: top;"


Error: Process completed with exit code 1.`

**Comment by scosman** [comment]
@evlim cool work!

Where's this at? I assume it's a full Svelte 5 port, and not just email as the title indicates 😀. Is it ready or still working on it?

Was the first commit just the regular tool or did it already have some of your work mixed in? For code reviewing I'd like to swap out the automatic migration from project specific changes.

re:email - I'll think on that. A few ways to solve, including just changing template or doing plaintext as you mention.

**Comment by evlim** [comment]
re:email I also thought about moving the email content to a separate file outside of src, for example in static. But that can lead to XSS attack.

**Comment by scosman** [comment]
@evlim doing some weird branching to merge this in steps, but making it's way in

**Pull request merged**
