### PR TITLE
feat: add sitemap.xml

### LINKED ISSUE #130: Add sitemap
This looks great. Hopefully templates like these will help the SvelteKit community to grow!

For SEO, it's missing a sitemap and robots.txt.

I might suggest Super Sitemap: https://github.com/jasongitmail/super-sitemap (I'm the author & searched deeply for a good one before building this.)

```ts
// /src/routes/sitemap.xml/+server.ts
import * as sitemap from 'super-sitemap';
import type { RequestHandler } from '@sveltejs/kit';

export const prerender = true;

export const GET: RequestHandler = async () => {
  return await sitemap.response({
    origin: 'https://example.com',
    excludeRoutePatterns: [
      '.*\\(admin\\).*', // i.e. exclude routes within admin group
    ],
  });
};
```
If you decide to add it, remember to include the `(admin)` group within the `excludeRoutePatterns` to omit those from your sitemap, and any others you might want to exclude.

Since your blog consists of svelte files, all those routes will be included automatically.

### PR DESCRIPTION
**Pull request by jasongitmail**
Closes #130 

## Summary by CodeRabbit

- **New Features**
	- Added a "Sitemap" section to the documentation for improved navigation and user experience.
	- Introduced a sitemap generation feature to enhance SEO and site navigation capabilities.
  
- **Dependencies**
	- Added `super-sitemap` library to improve sitemap management.

### CODE REVIEW

**Comment by scosman** [comment]
@jasongitmail Missing files? I fixed formatting errors but I'm getting build errors.

You can run the following locally to perform all the checks

```
npm run format_check
npm run lint
npm run build
npm run check
npm run test_run
```

**Comment by jasongitmail** [comment]
I pushed a commit for formatting. All checks passing. 

Nope, not missing files. If there's a build error, it's most likely not super-sitemap related. But lmk what error you're seeing if any.

**Comment by scosman** [comment]
I just forgot to `npm install` 🤦. Will take a look!

**Comment by scosman** [comment]
@jasongitmail thanks!

**Comment by jasongitmail** [comment]
haha that happens! You're welcome 🙂

**Pull request merged**
