### PR TITLE
Daisy UI 4 staging

### PR DESCRIPTION
**Pull request by scosman**
@keybits - Cloudflare should spin up staging URL here

### CODE REVIEW

**Comment by scosman** [comment]
https://daisy-ui-4-staging.saasstarter.pages.dev

**Comment by scosman** [comment]
Screenshot 2024-03-12 at 11 33 17 AM

Hovering "sign in" button needs a fix. Loses it's color on hover.

**Comment by scosman** [comment]
@keybits Mind making these fixes? You can make them in either branch. Just had to use the second one to get Cloudflare to spin up a preview.

**Comment by keybits** [comment]
Thanks for checking. Happy to make the changes. (I kind of like the brighter red though 😉)

Will update in the next day or two.

**Comment by scosman** [comment]
They are nice colors, but they don't work with the default theme. Saturation is way off -- everywhere else we use desaturated colors. And readability is poor with our default font color.

**Comment by scosman** [comment]
Thanks @keybits !

**Pull request merged**
