### PR TITLE
migrate to new supabase ssr auth package

### PR DESCRIPTION
**Pull request by kizivat**
As I [commented](https://github.com/CriticalMoments/CMSaasStarter/issues/29#issuecomment-2101742430) on  #29 there are still few

```
Using the user object as returned from supabase.auth.getSession() or from some supabase.auth.onAuthStateChange() events could be insecure! This value comes directly from the storage medium (usually cookies on the server) and many not be authentic. Use supabase.auth.getUser() instead which authenticates the data by contacting the Supabase Auth server.
```

warnings being logged. I'm unable to locate where they are coming from atm, but I'm opening this draft PR in case someone would like to have a look.

### CODE REVIEW

**Comment by scosman** [comment]
Very cool! Are you planning on updating once you find the remaining issues you described in #29? I'll hold off a detailed CR until then, probably.

**Comment by kizivat** [comment]
Yes, I'll have a look at it in a few hours.

**Comment by kizivat** [comment]
It looks like the warnings originate from `@supabase/auth-ui-svelte`. I'll be reimplementing the forms in my fork using form actions anyway.

I wanted to make PR fixing this into the [supabase/auth-ui](https://github.com/supabase-community/auth-ui), but it says it's in "Maintenance mode" which I suppose means that the PR would go unmerged for a while.

So we have a few options here. I'd be interested in hearing which one would you prefer, @scosman 

1. go ahead with this PR and merge it anyway even with the annoying Supabase warnings; add custom auth forms in later PR
3. add custom auth forms implementation to this PR
4. close this PR; stick to auth-helpers for now

**Comment by daniellovera** [comment]
I'd been meaning to add those stripe_customers definitions back to this repo, so I noticed you also added an id prop. Should that also be added to the creation of that table?

https://github.com/CriticalMoments/CMSaasStarter/blob/7904d416d2c72ec75f42fbf51e9e64fa74062ee6/database_migration.sql#L27

**Comment by kizivat** [comment]
> I'd been meaning to add those stripe_customers definitions back to this repo, so I noticed you also added an id prop. Should that also be added to the creation of that table?
> 
> https://github.com/CriticalMoments/CMSaasStarter/blob/7904d416d2c72ec75f42fbf51e9e64fa74062ee6/database_migration.sql#L27

You're right, there should be no `id`. Neither in select nor update I'll be removing it soon. Thank you.

**Comment by kizivat** [comment]
I made this ready for review so you could merge if needed. As you mentioned in #65 - it's a security concern. I believe #65 could have missed some spots (maybe not, not sure) though.

Weird supabase warnings can wait.

**Comment by scosman** [comment]
@kizivat can you check the security concern? I think I got them all. I completely removed the old method so would have caused build errors if not (I think). That's urgent because... security. Should split that out into the minimal PR if there is anything left.

For the rest: on vacation so won't be able to review till next week! But excited to get this in.

**Comment by kizivat** [comment]
> @kizivat can you check the security concern? I think I got them all. I completely removed the old method so would have caused build errors if not (I think). That's urgent because... security. Should split that out into the minimal PR if there is anything left.
> 
> 
> 
> For the rest: on vacation so won't be able to review till next week! But excited to get this in.

You're right, you got them all, just double checked. I didn't notice you've removed original `getSession` the first time I glanced the commit, sorry.

**Comment by scosman** [comment]
Thanks again for this PR. Looks good for quality (not final pass but initial looks good).

However: those errors sure are annoying!

I do think almost all are originating in our code. The fix suggested here (bit too much of a hack for my liking) does reduce the volume by 95%: https://github.com/supabase/auth-js/issues/873#issuecomment-2081467385 - now the code in question does come straight from the supabase guide.... 

Lots of other folks have the issue too, including after following latest official guides: https://github.com/supabase/auth-js/issues/873

I'm hoping they update docs and/or lib with an approved approach, and am inclined to wait for that. Better old system than one firing lots of security warnings. 

Also would take this if you can find a clean way to fix this. Potentially the forms you mention, and the a fix to getSafeSession like the ones suggested in the link above?

**Comment by scosman** [comment]
This seems to be the issue we're waiting on: https://github.com/supabase/auth-js/issues/888

**Comment by scosman** [comment]
@kizivat Does this change work with `"@supabase/auth-helpers-sveltekit": "^0.11.0",`? I found that worked around the blocker on another PR.

**Comment by kizivat** [comment]
> @kizivat Does this change work with `"@supabase/auth-helpers-sveltekit": "^0.11.0",`? I found that worked around the blocker on another PR.

well, this change removes the `@supabase/auth-helpers-sveltekit` dep altogether.

**Comment by scosman** [comment]
haha, of course.

Okay, let's wait until https://github.com/supabase/auth-js/issues/888 is resolved then.

**Comment by mez0ru** [comment]
Just wanted to add something to this pull request.

I tried to migrate to the ssr auth myself, and I managed to suppress all warnings. By not using `session.user`, but instead using the `user` returned from the getSafeSession function from hooks directly whenever trying to access the user data.
using `delete session.user;` would help you with that if you don't know when you are actually calling the session to get the user data.
This solved the issue completely for me, so I think waiting for a fix is not good as it's actually considered a bad practice now from the vibe I get on the people commenting on this issue.

**Comment by scosman** [comment]
@mez0ru can you share the code? Is it really just a `delete session.user`?

I had played around with this approach, but found it broke things (supabase expects session to have a user). I can't recall what though. I've seem similar options where they delete it, then replace it with the user from getUser, but the code was ugly and didn't look robust to future issues.

**Comment by mez0ru** [comment]
@scosman

I would like to, but my code is kinda messy and I already overwritten the template a bit. I'm still not 100% sure it supressed it, because there is a rare occasion of the log popping up after a while. When I'm sure I fixed it completely. I will try to replicate my setup on the template and share the code.

The key I think, is never using session, instead use `user` to check for session. Only use session when you are actually invalidate it, or check if it will expire. I tried logging out, and logging in, clicking all pages... but no logs are shown for now. I will keep you updated.

**Comment by scosman** [comment]
Try the change password functionality / settings too. I assume we need that there (but it's not fresh in my mind).

**Comment by mez0ru** [comment]
I noticed that using this method, is actually much much slower. I made a protected route, the getUser method inside supabase.auth takes around 200ms. I don't think users will enjoy this. It should be instantaneous. I think it's definitly a bug on supabase's part. It's their over sensitivity to any security vulnerability. Like I just want to know if the user is logged in or not, not to revalidate it on their servers every time the user enters a route.
I'm not sure if I will go this route, as I don't like how broken their practices are, even the docs don't help.
Sorry for my rambling, I don't think I will continue doing this, so I might migrate to lucia or something else entirely.
Thank you so much for your hard work on this template.

**Comment by analytically** [comment]
Is this functional?

**Comment by scosman** [comment]
@analytically it works. Just waiting a very long time on a fix to supabase so it doesn't log a ton of security warnings: https://github.com/supabase/auth-js/issues/888

@kizivat looks like there are some work arounds to hide the log in the issue thread. Interested in taking this change in with one of those? Waiting for a real fix hasn't exactly been fruitful 😀

**Comment by NDruce** [comment]
Better to make auth via [AuthJs](https://authjs.dev/)

**Comment by kizivat** [comment]
> @analytically it works. Just waiting a very long time on a fix to supabase so it doesn't log a ton of security warnings: [supabase/auth-js#888](https://github.com/supabase/auth-js/issues/888)
> 
> @kizivat looks like there are some work arounds to hide the log in the issue thread. Interested in taking this change in with one of those? Waiting for a real fix hasn't exactly been fruitful 😀

Yeah, looks promising. I'll look at it and update this PR if it works out. Thanks for pointing it out.

**Pull request merged**
